#ifndef RAYLEIGHTAYLOR_H
#define RAYLEIGHTAYLOR_H

#include <memory>

#include "src/core/Physics.H"
#include "src/physics/RayleighTaylorFieldInit.H"
#include "src/core/Field.H"

namespace kynema_sgf {

/** Rayleigh Taylor physics
 *  \ingroup physics
 *
 *  \sa RayleighTaylorFieldInit
 */
class RayleighTaylor : public Physics::Register<RayleighTaylor>
{
public:
    static std::string identifier() { return "RayleighTaylor"; }

    explicit RayleighTaylor(const CFDSim& sim);

    ~RayleighTaylor() override = default;

    //! Initialize the density and velocity fields for RayleighTaylor
    //! simulations
    void initialize_fields(int level, const amrex::Geometry& geom) override;

    void post_init_actions() override {}

    void post_regrid_actions() override {}

    void pre_advance_work() override {}

    void post_advance_work() override {}

private:
    Field& m_velocity;
    Field& m_density;

    //! RayleighTaylor field initializer instance
    std::unique_ptr<RayleighTaylorFieldInit> m_field_init;
};

} // namespace kynema_sgf

#endif /* RayleighTaylor_H */
